### ISSUE TITLE
3.x branch is broken

### ISSUE THREAD

**Issue by o01eg** [bend-n/godot-builds#1]
I forked `3.x` to build `3.5.2-stable` godot and it looks like it got broken with Scons: https://github.com/o01eg/godot-builds/actions/runs/4457048961

```
  scons: Reading SConscript files ...
  TypeError: sequence index must be integer, not 'slice':
    File "/home/runner/work/godot-builds/godot-builds/godot/SConstruct", line 449:
      detect.configure(env)
    File "/home/runner/work/godot-builds/godot-builds/godot/./platform/x11/detect.py", line 369:
      env.ParseConfig("pkg-config libpulse --cflags")  # Only cflags, we dlopen the library.
    File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/SCons/Environment.py", line 1773:
      return function(self, self.backtick(command), unique)
    File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/SCons/Environment.py", line 1767:
      return env.MergeFlags(cmd, unique)
    File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/SCons/Environment.py", line 1095:
      for v in orig[::-1]:
```

I suppose it could be fixed with https://github.com/godotengine/godot/commit/62b6529fed02d1076c6eb73e9c2c6d48e2349a49

**Comment by bend-n** [comment]
I should be able to pin the version of scons down.

**Comment by o01eg** [comment]
Yes, build passes with fix.

**Comment by bend-n** [comment]
@o01eg are you sure? my run hasnt fully worked yet.. https://github.com/bend-n/godot-builds/actions/runs/4458824790/jobs/7831122686

**Comment by o01eg** [comment]
I've seen previous error gone so expected other jobs will be successful.

**Comment by bend-n** [comment]
Okay, so the build worked, yes, but it didnt make a new release properly, released to the 3.5 release... https://github.com/bend-n/godot-builds/actions/runs/4458824790/jobs/7831145209

The docker container is also tagged 3.5.
I believe its because of this: 
https://github.com/bend-n/godot-builds/blob/d5c6726b911de5a1e8ad183dbebd659252a676c9/.github/actions/get-version/action.yml#L15

**Comment by bend-n** [comment]
Okay, I think ive got it to work, but im going to rebuild 3.5 and build 3.5.1 before i close this.

**Comment by o01eg** [comment]
Looks like it somehow worked for me, not yet tried resulting image: https://github.com/o01eg/godot-builds/actions/runs/4458882825

**Comment by bend-n** [comment]
All the builds succeeded, and are tagged properly.
