### ISSUE TITLE
Headless godot missing

### ISSUE THREAD

**Issue by o01eg** [bend-n/godot-builds#2]
After update to new images command line

```bash
godot --no-window --disable-render-loop --video-driver Dummy --gdnative-generate-json-api godot-api.json
```

Started to produce error:

```
Unknown video driver 'Dummy', aborting.
Valid options are 'GLES3' and 'GLES2'.
```
https://github.com/freeorion/freeorion/actions/runs/4460076834/jobs/7832978126

If I try to use `--headless` described in 

https://github.com/bend-n/godot-actions/blob/020709893242606e0f81e66e2ab211df84ebc5c3/.github/actions/export/action.yml#L42

I got error:

```
v3.5.2.stable.bendn.170ba337a
ERROR: X11 Display is not available
   at: initialize (platform/x11/os_x11.cpp:143)
```
https://github.com/o01eg/freeorion/actions/runs/4460330670/jobs/7833400966

**Comment by bend-n** [comment]
Have you tried
```bash
godot --no-window --gdnative-generate-json-api godot-api.json
```
`--video-driver Dummy` doesnt work on official 3.5 either, and `--headless` is 4.x only.

**Comment by o01eg** [comment]
`--no-window` get same error:

https://github.com/o01eg/freeorion/actions/runs/4460525904/jobs/7833725884

**Comment by bend-n** [comment]
Im not quite sure whats happening, maybe its a upstream bug? But it isnt anything specific to my builds i think...

**Comment by o01eg** [comment]
Shouldn't there was separate godot binary built with `platform=server`?

**Comment by bend-n** [comment]
~~`server` isnt a platform.~~ (oh, was checking on 4.x)

You could also try `xvfb-run godot` but im not sure how that would work.

**Comment by o01eg** [comment]
That works, we use it to test godot in snap. But still it strange it worked before.

**Comment by o01eg** [comment]
As I see in my release https://github.com/o01eg/godot-builds/releases/tag/3.5 headless version was present.

**Comment by bend-n** [comment]
Hmm, okay.. Will see to adding it back.

**Comment by o01eg** [comment]
`server` platform existed in old commits:

https://github.com/bend-n/godot-builds/blob/33faf5f6799aaf0d70455179200c5a3a0585c48a/.github/workflows/reusable-build.yml#L231-L252

https://github.com/bend-n/godot-builds/blob/33faf5f6799aaf0d70455179200c5a3a0585c48a/.github/actions/build-upload-image/action.yml#L26-L32

**Comment by o01eg** [comment]
I've updated 3.5.2 to 3.6 and run into this issue again https://github.com/o01eg/freeorion/actions/runs/13213242883/job/36889400569
