### ISSUE TITLE
version.txt missing from export templates?

### ISSUE THREAD

**Issue by koutsie** [bend-n/godot-builds#6]
Hey, I think the current export templates are missing the version.txt file :(
![image](https://github.com/bend-n/godot-builds/assets/18449778/b55542e9-79b4-41a4-8350-906b200cb7e3)

**Comment by bend-n** [comment]
what version.txt

**Comment by bend-n** [comment]
your not supposed to use the import dialog, you can just put them in the relevant folder
after unzipping

**Comment by koutsie** [comment]
That explains it haha.
Should probably make the AUR package place them in .local/share/godot/$version/export_temples then too haha - tho idk if this'd cause version conflics if the user has multiple versions installed :shrug:

**Comment by bend-n** [comment]
Thats not possible, PKGBUILD is not able to access ~. Hence, it prints this message, which you might have seen: 
> templates in /usr/share/godot/export_templates/4.2.1.stable, please link to ~/.local/share/godot/export_templates/4.2.1.stable

**Comment by koutsie** [comment]
I did not haha, alright thanks :clap:
